language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: sundust
  - GAMEKIT_APPLICATION_PACKAGE: fistmage.game
  - GAMEKIT_APPLICATION_MAIN_CLASS: fistmage-game
  - PATH: ~/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
  - secure: "LJViHeQhDDc9Zm+ki6IOOPvJUAlmkIDw0uFJOw7AKEVO8FmUiAt0twiT+QLqKBRxJjH/FUZpWwevmnFaZrhlqnGOmcfloKyFxP2r49AQld/+yAs4RnuC0hmgsQh4ZzFb4Pd/DapttFU64KVvvhXOndwN7Jfl6mI7Zx6BH38lkwY9niafqCSxJ7b/csihJLiC2PTEitsflaQ5NzkodwQK71SIM0mzBWfO6sDFGkEEpHquMjf4qEJ2ZZVH6TSo9clqM/JkgcxMM2i8h9aypI7badl6dJCVCb3GugFJbQyxpzX0PADCEAEMdrWXXO3AmsHv/rpPHw7Ee+ZrhT7/c9g7jL/reX2oX3Ijey4Ud4Ev7EDPceeSGM1dKljLhHGzrtTpDsZD4q2QsAZSet4zgLz1OwPpGt6KoJJ/5gLKUEpA6r9HWGvFhsN1Z85lW+u85RPQOQBm/1d+lTexvudLavOAddtNs7tJN8ezV8hagN+ceAHfkXtXnsvEi9k8sryAWTjpGOCfSOZJqrHY5jLbZPk1t7NKREVpR6cT+ugCTSO3zC1k5LwnhgXWY5youW5cn74rEUHL/O7fN4TXxpLD30GEhhVYTxtsrGSXy+sL2d5X3kj77LFvOKEsLzFyx08TAiaKLs7BdjR8OWNRFQj11QtgjPcTMEgOiIKSmVoCtyobcig="

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh

cache:
  directories:
  - "$HOME/.config/common-lisp/"

script:
  - >
    lisp $HOME/bodge/scripts/build-experimental-gamekit-system.lisp
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR
    t

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
